### ISSUE TITLE
请问有中文版本吗

### ISSUE THREAD

**Issue by 1SingleFeng** [BatsResearch/bonito#32]

**Comment by nanyyyyyy** [comment]
Hi, thank you so much for your interest in our work! However, I'm sorry, but Bonito only supports English.

**Comment by zhanglt** [comment]
I tried to train bointo to make it support Chinese and acceptable.
[kitsdk/bonito-chinese-v1](https://huggingface.co/kitsdk/bonito-chinese-v1)
