### ISSUE TITLE
Build multiple QA pairs for long document

### ISSUE THREAD

**Issue by tqdo** [BatsResearch/bonito#40]
First of all thank you for a very useful package. My question is: if I have a long text document, is there any way bonito can create multiple QA pairs that cover the entire knowledge of the document? Looking at the examples, it looks like I need to break up the long document into smaller chunks manually by myself first, then feed each chunk to bonito to create a QA pair for that chunk.

**Comment by nanyyyyyy** [comment]
Thank you for your interest in Bonito! You're right, though, unfortunately, Bonito can't generate multiple QA pairs from a long context input at the moment at a time. Breaking the input into smaller chunks would be a nice solution. Thanks!
