### ISSUE TITLE
Whether it is possible to load a local model

### ISSUE THREAD

**Issue by huangzsdy** [BatsResearch/bonito#42]
When i execute this code:

bonito = Bonito("BatsResearch/bonito-v1") 

error occurs,
 "requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bonitov1/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6bc04dd110>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 63577d75-f6b6-4a39-a96b-d85f85b3f6ab)')", 

so i download this model by huggingface-cli, but still same error occurs. Is it possible to load the model locally when I execute "bonito = Bonito("BatsResearch/bonito-v1") " ?

![image](https://github.com/user-attachments/assets/c16dbdbe-462e-41e4-98e0-57530bfc2f7f)

**Comment by nanyyyyyy** [comment]
Hi, thank you for your interest in our work! yes, you can load bonito just like any other huggingface models. with `AutoModelForCausalLM.from_pretrained()`

**Comment by huangzsdy** [comment]
> Hi, thank you for your interest in our work! yes, you can load bonito just like any other huggingface models. with `AutoModelForCausalLM.from_pretrained()`

Thanks for your reply! 
But it still report an error, 

![image](https://github.com/user-attachments/assets/d3d29203-8a55-48bf-95c5-c7d78c331cae)
"ValueError: Unrecognized model in bonitov1. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, bros, camembert, canine, chameleon, chinese_clip, chinese_clip_vision_model, clap, clip, clip_text_model, clip_vision_model, clipseg, clvp, code_llama, codegen, cohere, conditional_detr, convbert, convnext, convnextv2, cpmant, ctrl, cvt, dac, data2vec-audio, data2vec-text, data2vec-vision, dbrx, deberta, deberta-v2, decision_transformer, deformable_detr, deit, depth_anything, deta, detr, dinat, dinov2, distilbert, donut-swin, dpr, dpt, efficientformer, efficientnet, electra, encodec, encoder-decoder, ernie, ernie_m, esm, falcon, falcon_mamba, fastspeech2_conformer, flaubert, flava, fnet, focalnet, fsmt, funnel, fuyu, gemma, gemma2, git, glm, glpn, gpt-sw3, gpt2, gpt_bigcode, gpt_neo, gpt_neox, gpt_neox_japanese, gptj, gptsan-japanese, granite, granitemoe, graphormer, grounding-dino, groupvit, hiera, hubert, ibert, idefics, idefics2, idefics3, ijepa, imagegpt, informer, instructblip, instructblipvideo, jamba, jetmoe, jukebox, kosmos-2, layoutlm, layoutlmv2, layoutlmv3, led, levit, lilt, llama, llava, llava_next, llava_next_video, llava_onevision, longformer, longt5, luke, lxmert, m2m_100, mamba, mamba2, marian, markuplm, mask2former, maskformer, maskformer-swin, mbart, mctct, mega, megatron-bert, mgp-str, mimi, mistral, mixtral, mllama, mobilebert, mobilenet_v1, mobilenet_v2, mobilevit, mobilevitv2, moshi, mpnet, mpt, mra, mt5, musicgen, musicgen_melody, mvp, nat, nemotron, nezha, nllb-moe, nougat, nystromformer, olmo, olmo2, olmoe, omdet-turbo, oneformer, open-llama, openai-gpt, opt, owlv2, owlvit, paligemma, patchtsmixer, patchtst, pegasus, pegasus_x, perceiver, persimmon, phi, phi3, phimoe, pix2struct, pixtral, plbart, poolformer, pop2piano, prophetnet, pvt, pvt_v2, qdqbert, qwen2, qwen2_audio, qwen2_audio_encoder, qwen2_moe, qwen2_vl, rag, realm, recurrent_gemma, reformer, regnet, rembert, resnet, retribert, roberta, roberta-prelayernorm, roc_bert, roformer, rt_detr, rt_detr_resnet, rwkv, sam, seamless_m4t, seamless_m4t_v2, segformer, seggpt, sew, sew-d, siglip, siglip_vision_model, speech-encoder-decoder, speech_to_text, speech_to_text_2, speecht5, splinter, squeezebert, stablelm, starcoder2, superpoint, swiftformer, swin, swin2sr, swinv2, switch_transformers, t5, table-transformer, tapas, time_series_transformer, timesformer, timm_backbone, trajectory_transformer, transfo-xl, trocr, tvlt, tvp, udop, umt5, unispeech, unispeech-sat, univnet, upernet, van, video_llava, videomae, vilt, vipllava, vision-encoder-decoder, vision-text-dual-encoder, visual_bert, vit, vit_hybrid, vit_mae, vit_msn, vitdet, vitmatte, vits, vivit, wav2vec2, wav2vec2-bert, wav2vec2-conformer, wavlm, whisper, xclip, xglm, xlm, xlm-prophetnet, xlm-roberta, xlm-roberta-xl, xlnet, xmod, yolos, yoso, zamba, zoedepth“


it seems like model downloaded by huggingface-cli doesn't work. Could you please share the model via Google Drive or some other way?
Thanks !

**Comment by nanyyyyyy** [comment]
sorry, I wasn't very clear. It should be `AutoModelForCausalLM('BatsResearch/bonito-v1')` with some other configurations depending on your use case. (I am showing the simplest way). and I think there's also a typo in the code.

**Comment by huangzsdy** [comment]
I am sorry to bother you, but it still failed.
my code is as follows:
![image](https://github.com/user-attachments/assets/dcbfb25e-b73a-4350-88e4-238519e4a563)

It occurred error at this line.
" model = AutoModelForCausalLM.from_pretrained("bonito_v1")
"
![image](https://github.com/user-attachments/assets/39859700-4d23-4156-86bf-3571ee18a08a)


"bonito_v1" contains files which were downloaded from https://huggingface.co/BatsResearch/bonito-v1/tree/main
![image](https://github.com/user-attachments/assets/de7c06d4-7e6f-46ae-a4d8-65696f11961f)

If i rewrite that line:
"model = AutoModelForCausalLM("bonito_v1")"
The following error message is displayed:
![image](https://github.com/user-attachments/assets/343d6dd9-3e4a-4c4a-a355-b5a3345b133f)


Could you please help me ? I am so confused

**Comment by huangzsdy** [comment]
> sorry, I wasn't very clear. It should be `AutoModelForCausalLM('BatsResearch/bonito-v1')` with some other configurations depending on your use case. (I am showing the simplest way). and I think there's also a typo in the code.

I am sorry to bother you, but it still failed.
my code is as follows:
![image](https://github.com/user-attachments/assets/dcbfb25e-b73a-4350-88e4-238519e4a563)

It occurred error at this line.
" model = AutoModelForCausalLM.from_pretrained("bonito_v1")
"
![image](https://github.com/user-attachments/assets/39859700-4d23-4156-86bf-3571ee18a08a)


"bonito_v1" contains files which were downloaded from https://huggingface.co/BatsResearch/bonito-v1/tree/main
![image](https://github.com/user-attachments/assets/de7c06d4-7e6f-46ae-a4d8-65696f11961f)

If i rewrite that line:
"model = AutoModelForCausalLM("bonito_v1")"
The following error message is displayed:
![image](https://github.com/user-attachments/assets/343d6dd9-3e4a-4c4a-a355-b5a3345b133f)


Could you please help me ? I am so confused

**Comment by nanyyyyyy** [comment]
try `BatsResearch/bonito-v1` instead of `bonito-v1`

**Comment by huangzsdy** [comment]
> try `BatsResearch/bonito-v1` instead of `bonito-v1`

It still reports same error...
![image](https://github.com/user-attachments/assets/90fb7070-77cd-4316-8557-bfba05f8608d)


![image](https://github.com/user-attachments/assets/6cad4f11-ed45-41f8-86db-509565d11f13)
btw, my server cannot open Google to download this model...

**Comment by nanyyyyyy** [comment]
If you have already downloaded the model locally, you should replace the model name with the local model path. [transformers Auto Classes](https://huggingface.co/docs/transformers/main/en/model_doc/auto#transformers.AutoModel.from_pretrained)

**Comment by huangzsdy** [comment]
> If you have already downloaded the model locally, you should replace the model name with the local model path. [transformers Auto Classes](https://huggingface.co/docs/transformers/main/en/model_doc/auto#transformers.AutoModel.from_pretrained)

Yes！Iput the local model path in that function. 
![image](https://github.com/user-attachments/assets/6cec90dc-c5be-4a05-b3a6-53236db5a2f0)

Error occrurs, 

![image](https://github.com/user-attachments/assets/8e108fdd-28bc-4cf5-bc00-7a300eb88acb).

Could you please do the same thing i did? use local model path, let's see if the output is the same as mine

**Comment by huangzsdy** [comment]
> If you have already downloaded the model locally, you should replace the model name with the local model path. [transformers Auto Classes](https://huggingface.co/docs/transformers/main/en/model_doc/auto#transformers.AutoModel.from_pretrained)

I figure it out. Because that memory of my server is not enough, so I change a new one.
But there comes new error!
![image](https://github.com/user-attachments/assets/b8afc53c-d1ee-4f49-9e12-ebf766b71775)
If I can not use "mistral" model_type, which type should I use?
![image](https://github.com/user-attachments/assets/2d22e156-eac6-4801-8862-4c2a55bb7630)

**Comment by nanyyyyyy** [comment]
If you are using `AutoModelForCausalLM.from_pretrained()`, you need to follow the generation pipeline of the `Transformers` library. The `generate_tasks` method is defined in our bonito GitHub library. I assume you are using `AutoModelForCausalLM.from_pretrained()` but calling the `generate_tasks` method. it's not about model_type

**Comment by huangzsdy** [comment]
> If you are using `AutoModelForCausalLM.from_pretrained()`, you need to follow the generation pipeline of the `Transformers` library. The `generate_tasks` method is defined in our bonito GitHub library. I assume you are using `AutoModelForCausalLM.from_pretrained()` but calling the `generate_tasks` method. it's not about model_type

yes, but if I use generation pipline of the Transformers library,  whether it means I should create a function that mimics the function "generate_tasks" ? 
That's  will become complicated .

Could you please implement a function to adapt it to users who use AutoModelForCausalLM.from_pretrained() ?
