### ISSUE TITLE
Maximum sequence length error

### ISSUE THREAD

**Issue by grandintegrator** [BatsResearch/bonito#7]
Hey team, really excited to get started with your repo but I am running into the following error:

```
ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (16816). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
File <command-609584913430219>, line 5
```

Code I ran: 

```
from bonito import Bonito, SamplingParams
from datasets import load_dataset

# Initialize the Bonito model
bonito = Bonito("BatsResearch/bonito-v1")
```

Hardware: I am running on a `g5.8xlarge` instance on AWS which corresponds to a single A10G with 128 GiB of memory, and 600 GB of local NVMe storage. 

Any insights appreciated!

**Comment by nihalnayak** [comment]
Thanks for this issue. This error is from the `vllm` package. To fix this issue, you need to set the `max_model_len` < KV cache.

To change the `max_model_len`, try the following: 
```
bonito = Bonito("BatsResearch/bonito-v1", max_model_len=10000)
```

Let us know if this works for you! 

For more details, see https://github.com/vllm-project/vllm/issues/2418#issuecomment-1895696282

**Comment by grandintegrator** [comment]
Fixed - thanks heaps!

**Comment by grandintegrator** [comment]
Thank you!
