### ISSUE TITLE
ModuleNotFoundError: No module named 'bonito'

### ISSUE THREAD

**Issue by MatteoRiva95** [BatsResearch/bonito#8]
Hello everyone,

I am trying to use Bonito on Colab (T4 GPU) and I am following these commands:

!pip install -e git+https://github.com/BatsResearch/bonito#egg=bonito

from bonito import Bonito, SamplingParams
from datasets import load_dataset

bonito = Bonito("BatsResearch/bonito-v1")

but it returns this error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-20-d44269ada425>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from bonito import Bonito, SamplingParams
      2 from datasets import load_dataset
      3 
      4 # Initialize the Bonito model
      5 bonito = Bonito("BatsResearch/bonito-v1")

ModuleNotFoundError: No module named 'bonito'

How can I solve it? Can you help me?

Thank you so much in advance!

**Comment by nihalnayak** [comment]
Thanks for posting this issue. Could you try this command: 
```
!pip install -U git+https://github.com/BatsResearch/bonito.git
```
It seems to work for me.

**Comment by MatteoRiva95** [comment]
@nihalnayak Thank you so much for your fast reply! 
Wonderful! It has been installed :)

But unfortunately when I lauch this command, it gives an error:

from bonito import Bonito, SamplingParams
from datasets import load_dataset

bonito = Bonito("BatsResearch/bonito-v1")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-11-d44269ada425>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 # Initialize the Bonito model
----> 5 bonito = Bonito("BatsResearch/bonito-v1")
      6 

6 frames
[/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py](https://localhost:8080/#) in _check_if_gpu_supports_dtype(torch_dtype)
    298         if compute_capability[0] < 8:
    299             gpu_name = torch.cuda.get_device_name()
--> 300             raise ValueError(
    301                 "Bfloat16 is only supported on GPUs with compute capability "
    302                 f"of at least 8.0. Your {gpu_name} GPU has compute capability "

ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla T4 GPU has compute capability 7.5. You can use float16 instead by explicitly setting the`dtype` flag in CLI, for example: --dtype=half.

Is it possible to solve it too?

Thank you again!

**Comment by nihalnayak** [comment]
Amazing! We are looking at this issue on our end. We will keep you posted when we solve this issue. Thanks for letting us know. 

Closing this issue for now.
